name: med-condaenv
channels:
- conda-forge
- accessnri
variables:
  CARTOPY_USER_BACKGROUNDS: /g/data/xp65/public/apps/cartopy-data/backgrounds
dependencies:
- fs
- python>=3.9
- pip
- pytest
- pytest-cov
- autopep8
- pyyaml
- cdo>=1.9.5 # pinned for solver stability
# pinning matplotlib to 3.5.3 temporarily until plotnine issue is fixed https://github.com/has2k1/plotnine/issues/620
- matplotlib==3.5.3  #
- jinja2
- ilamb
- dask
- iris
- intake
- netcdf4<=1.6.0 ### Workaround for https://github.com/pydata/xarray/issues/7079
- numpy>=1.21 # Mule dependency
- pandas
- scipy
- h5py
- numba
- esmvaltool
- esmvaltool-python
- esmvaltool-ncl
- scikit-image
- jupyter
- jupyterlab
- jupyterlab_server
- jupyter_nbextensions_configurator
- jupyter_contrib_nbextensions
- jupyter-server-proxy
- jupyter-book
- jupyter-resource-usage
- greenlet ### Dependency of... something?
- objgraph ### Unlisted dependency of greenlet
- asyncssh
- pip:
  - railroad-diagrams ### Unlisted dependency of pip and pyparsing

