name: Build and test conda env
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      - name: Sync repository to Gadi
        ### Latest at time of writing
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: gadi.nci.org.au
          TARGET: ${{secrets.GADI_REPO_PATH}}
          KEY: ${{secrets.DEPLOY_KEY}}
          USER: ${{secrets.GADI_USER}}
      - name: Create Admin dirs on Gadi
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            source ${{secrets.GADI_REPO_PATH}}/scripts/install_config.sh
            source ${{secrets.GADI_REPO_PATH}}/scripts/functions.sh
            mkdir -p $ADMIN_DIR $JOB_LOG_DIR $BUILD_STAGE_DIR
            set_admin_perms $ADMIN_DIR $JOB_LOG_DIR $BUILD_STAGE_DIR
      - name: Build environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          command_timeout: 120m
          script: |
            export SCRIPT_DIR=${{secrets.GADI_REPO_PATH}}/scripts
            eval $( grep ADMIN_DIR $SCRIPT_DIR/install_config.sh )
            eval $( grep JOB_LOG_DIR $SCRIPT_DIR/install_config.sh )
            cd $JOB_LOG_DIR
            jobid=$( qsub -N build_conda -lncpus=1,mem=20GB,walltime=2:00:00,jobfs=50GB,storage=gdata/v45+scratch/v45+gdata/hh5+scratch/hh5 -v SCRIPT_DIR -P w40 -q copyq -Wblock=true "${SCRIPT_DIR}"/build.sh )
            job_stat=$?
            echo "========== JOB STDOUT =========="
            cat build_conda.o"${jobid//.gadi-pbs/}"
            echo "================================"
            echo "========== JOB STDERR =========="
            cat build_conda.e"${jobid//.gadi-pbs/}"
            echo "================================"
            exit $job_stat
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          script: |
            export SCRIPT_DIR=${{secrets.GADI_REPO_PATH}}/scripts
            eval $( grep ADMIN_DIR $SCRIPT_DIR/install_config.sh )
            eval $( grep JOB_LOG_DIR $SCRIPT_DIR/install_config.sh )
            cd $JOB_LOG_DIR
            jobid=$( qsub -N test_conda -lncpus=4,mem=20GB,walltime=0:20:00,jobfs=50GB,storage=gdata/v45+scratch/v45+gdata/hh5+scratch/hh5 -v SCRIPT_DIR -P w40 -Wblock=true "${SCRIPT_DIR}"/test.sh
            job_stat=$?
            echo "========== JOB STDOUT =========="
            cat test_conda.o"${jobid//.gadi-pbs/}"
            echo "================================"
            echo "========== JOB STDERR =========="
            cat test_conda.e"${jobid//.gadi-pbs/}"
            echo "================================"
            exit $job_stat